create extension if not exists vector;

create table public.coaching_documents (
  id bigint generated by default as identity primary key,
  source_url text not null,
  source_title text,
  content text not null,
  content_hash text not null unique,
  flaw_labels text[] not null default '{}',
  embedding vector(1536) not null,
  embedding_model text not null default 'openai/text-embedding-3-small',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index coaching_documents_source_url_idx
  on public.coaching_documents (source_url);

create index coaching_documents_flaw_labels_idx
  on public.coaching_documents using gin (flaw_labels);

create index coaching_documents_embedding_hnsw_idx
  on public.coaching_documents
  using hnsw (embedding vector_cosine_ops);

create trigger coaching_documents_set_updated_at
  before update on public.coaching_documents
  for each row execute function system.update_updated_at();

alter table public.coaching_documents enable row level security;

revoke all on table public.coaching_documents from anon, authenticated;
revoke all on sequence public.coaching_documents_id_seq from anon, authenticated;

create function public.match_coaching_documents(
  query_embedding vector(1536),
  match_count integer default 5,
  match_threshold double precision default 0.72,
  filter_flaw_label text default null
)
returns table (
  id bigint,
  source_url text,
  source_title text,
  content text,
  flaw_labels text[],
  metadata jsonb,
  similarity double precision
)
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  select
    document.id,
    document.source_url,
    document.source_title,
    document.content,
    document.flaw_labels,
    document.metadata,
    1 - (document.embedding <=> query_embedding) as similarity
  from public.coaching_documents as document
  where
    (
      filter_flaw_label is null
      or filter_flaw_label = any(document.flaw_labels)
    )
    and 1 - (document.embedding <=> query_embedding) >= match_threshold
  order by document.embedding <=> query_embedding
  limit match_count;
$$;

revoke all on function public.match_coaching_documents(
  vector,
  integer,
  double precision,
  text
) from public, anon, authenticated;
